### ISSUE TITLE
Issue with Blender on stage 5

### ISSUE THREAD

**Issue by realmworksxyz** [jonmatthis/freemocap#103]
Attached the error message. Any help is appreciated in getting the data to Blender.

fmc.RunMe(sessionID="sesh_2022-02-03_12_29_11", stage=5)
╔═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╗
║                                             Welcome to FreeMoCap ✨💀✨                                             ║
╚═════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Running sesh_2022-02-03_12_29_11 from P:\Assets\animation\FreeMocap_Data
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
Skipping Video Recording
Skipping Video Syncing
Skipping Calibration
Skipping 2d point tracking
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ C:\Users\aleksi\anaconda3\envs\freemocap-env\lib\site-packages\freemocap\fmc_runme.py:305 in     │
│ RunMe                                                                                            │
│                                                                                                  │
│   302 │   │   │   │                                                                              │
│   303 │   │   │   │   #blenderPath = Path(''C:\Program Files\Blender Foundation\Blender 2.93'')    │
│   304 │   │   │   │   #os.chdir(blenderExePath)                                                  │
│ > 305 │   │   │   output = subprocess.run([str(blenderPath), "--background", "--python", "free   │
│   306 │   │   │   print(output)                                                                  │
│   307 │   │   except:                                                                            │
│   308 │   │   │   console.print_exception()                                                      │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
UnboundLocalError: local variable 'blenderPath' referenced before assignment

**Comment by aaroncherian** [comment]
Hey, thanks for pointing this out! I've fixed this bug on our Github version of the code - if you're using the PyPi version of the code, keep an eye out for the next update.

**Comment by realmworksxyz** [comment]
Yesss, thank youuu!
