### ISSUE TITLE
list index out or range on stage 3

### ISSUE THREAD

**Issue by tomazsaraiva** [jonmatthis/freemocap#108]
Hey, I've followed the setup but I'm having the following on Stage 3 - Calibrate Capture Volume: list index out of range.

 Here are some screenshots of the error: 
![Image1](https://media.discordapp.net/attachments/760489602917466133/943142354674667582/unknown.png?width=671&height=676)
![Image2](https://media.discordapp.net/attachments/760489602917466133/943142354888564806/unknown.png?width=674&height=676).

Thanks a lot for any help.

**Comment by tomazsaraiva** [comment]
Hey, a single camera. Thanks

**Comment by aaroncherian** [comment]
yeah that would do it. So you need a minimum of two cameras for Freemocap to run properly. In this stage in particular (the calibration stage), the code uses the videos from multiple cameras to figure out their positions in 3D space, hence why it's failing with just one camera.

Having a single camera option is something on our list for further along in the future, but the way things are right now you need at least two cameras.

**Comment by tomazsaraiva** [comment]
ohh my bad! I probably missed that, thanks for your help. Will try it again tomorrow.
