### ISSUE TITLE
"Number of frames is not the same" error in 'fmc.RunMe()'

### ISSUE THREAD

**Issue by trentwirth** [jonmatthis/freemocap#11]
when running 'fmc.RunMe()' and the frames aren't the exact same number it kills the code

'''
In [4]: freemocap.RunMe()
Starting initialization for stage 1
100%|███████████████████████████████████████████████████████████████████████████████| 20/20 [00:05<00:00,  3.39it/s]
Proceeding to Stage One

Starting Video Recordings
Starting Cam1
Starting Cam2
width: 640.0 height: 480.0
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
width:OpenCV: F FMPEG: fallback to use tag 0x31637661/'avc1'
640.0 height: 480.0

Failed to load OpenH264 library: openh264-1.7.0-win64.dll
        Please check environment and/or download library: https://github.com/cisco/openh264/releases

[libopenh264 @ 000001807f725ac0] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
[libopenh264 @ 000001807f729a60] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
finished recordings

Starting Video Syncing
intervals: 4.0 8.0
using frames: 26 - 146 for Cam1
using frames: 27 - 147 for Cam2
starting detection: Cam1
starting detection: Cam2

Starting editing
Editing Cam1 from raw_cam1.mp4
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
[libopenh264 @ 000001807f78a2a0] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
Working... ---------------------------------------- 100% 0:00:00
Saved C:\WINDOWS\system32\Data\sesh_21-07-05_174330\SyncedVideos\sesh_21-07-05_174330_synced_Cam1.mp4

Editing Cam2 from raw_cam2.mp4
OpenCV: FFMPEG: tag 0x34363248/'H264' is not supported with codec id 28 and format 'mp4 / MP4 (MPEG-4 Part 14)'
OpenCV: FFMPEG: fallback to use tag 0x31637661/'avc1'
[libopenh264 @ 0000018060e3a6c0] Incorrect library version loaded
Could not open codec 'libopenh264': Unspecified error
Working... ---------------------------------------- 100% 0:00:00
Saved C:\WINDOWS\system32\Data\sesh_21-07-05_174330\SyncedVideos\sesh_21-07-05_174330_synced_Cam2.mp4

---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-4-2224aca7f986> in <module>
----> 1 freemocap.RunMe()

c:\users\trent\anaconda3\envs\fmc-pip\lib\site-packages\freemocap\__init__.py in RunMe()
    112         print("Starting Video Syncing")
    113         runcams.SyncCams(
--> 114             sesh, sesh.timeStampData, sesh.numCamRange, sesh.vidNames, sesh.camIDs
    115         )
    116     else:

c:\users\trent\anaconda3\envs\fmc-pip\lib\site-packages\freemocap\runcams.py in SyncCams(session, timeStampData, numCamRange, vidNames, camIDs)
     98         print()
     99         print('Starting editing')
--> 100         videotrim.VideoTrim(session,vidNames,frameTable,session.parameterDictionary,session.rotationInputs,numCamRange)
    101         session.session_settings['recording_parameters'].update({'numFrames':session.numFrames})
    102         #videotrim.createCalibrationVideos(session,60,parameterDictionary)

c:\users\trent\anaconda3\envs\fmc-pip\lib\site-packages\freemocap\webcam\videotrim.py in VideoTrim(session, vidList, ft, parameterDictionary, rotationState, numCamRange)
     67         print()
     68
---> 69     assert postTrimmingTotalNumFrames.count(postTrimmingTotalNumFrames[0]) == len(postTrimmingTotalNumFrames), "Number of frames in each synced video is not the same"
     70     session.postTrimmingNumFrames = postTrimmingTotalNumFrames[0]
     71     session.numFrames = postTrimmingTotalNumFrames[0]

AssertionError: Number of frames in each synced video is not the same
'''

**Comment by jonmatthis** [comment]
Ok, we're on it  👍

**Comment by aaroncherian** [comment]
@trentwirth can you email me/discord message me the session folder for this? It'll make troubleshooting easier

**Comment by aaroncherian** [comment]
(ideally) the issue should be fixed - the issue wasn't on the syncing side, but the openCV side of creating synced videos. specifically from having rotated videos that needed buffer frames. There was a bug with resizing the buffer frames during video rotation that kept them from being written to the synced video. I retested on Trent's data and it worked, and did some testing on some of my own videos and was able to both duplicate and fix the bug at will, so I think it's been taken care of.
