### ISSUE TITLE
Why could the tests be falling?

### ISSUE THREAD

**Issue by abitrolly** [jonmatthis/freemocap#30]
I tried to fix tests in #29 and once I installed `xvfb` they just started to hang. Before the hang the tests were failing with the error below. Not sure how to fix them.

```python
______________________ ERROR collecting freemocap_test.py ______________________
ImportError while importing test module '/home/travis/build/jonmatthis/freemocap/freemocap_test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../../virtualenv/python3.7.6/lib/python3.7/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
freemocap_test.py:13: in <module>
    freemocap.RunMe( stage = 1, useDLC=True,setDataPath=False)
freemocap/__init__.py:9: in RunMe
    fmc_runme.Run(sessionID,stage,useOpenPose,useMediaPipe,useDLC,dlcConfigPath,debug,setDataPath,userDataPath)
freemocap/fmc_runme.py:41: in Run
    import deeplabcut as dlc
../../../virtualenv/python3.7.6/lib/python3.7/site-packages/deeplabcut/__init__.py:26: in <module>
    mpl.use("WxAgg")
../../../virtualenv/python3.7.6/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py:307: in wrapper
    return func(*args, **kwargs)
../../../virtualenv/python3.7.6/lib/python3.7/site-packages/matplotlib/__init__.py:1307: in use
    switch_backend(name)
../../../virtualenv/python3.7.6/lib/python3.7/site-packages/matplotlib/pyplot.py:236: in switch_backend
    newbackend, required_framework, current_framework))
E   ImportError: Cannot load backend 'WXAgg' which requires the 'wx' interactive framework, as 'headless' is currently running
```

**Comment by aaroncherian** [comment]
So, I copied your travis yaml directly and pushed it to main, just to see what happened - I don't think I made any changes, and I think it actually seemed to run and load through, or at the very least the error I got wasn't related to the framework issue here. It stalled on the 'coverage run -m pytest' line, which might actually be more about us not really having proper tests set up than anything else? I'm not at all proficient on travisCI stuff just yet, so still have a lot to figure out. I attached the full log down below.

[travis_test1_7_27.txt](https://github.com/jonmatthis/freemocap/files/6887473/travis_test1_7_27.txt)

**Comment by abitrolly** [comment]
@aaroncherian that's exactly the problem I've got in https://app.travis-ci.com/github/jonmatthis/freemocap/builds/233393046#L623 after installing `xvfb`. The build log without `xvfb` is https://app.travis-ci.com/github/jonmatthis/freemocap/builds/233390719#L627

**Comment by aaroncherian** [comment]
ah okay, in that case, I *think* that set of errors (after installing `xvfb`), comes on our end from not writing up proper test/test cases. I think the line at the end of that log that says 'No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.' comes from us not having the log output anything when doing a test. Maybe? 

Either way, you made a ton of progress on this issue, and it's been much appreciated - I merged in your pull request on the tests and the yaml.

**Comment by abitrolly** [comment]
There is no Travis anymore, so maybe it won't be repeatable with GitHub Actions (#96),
