### ISSUE TITLE
Request for sample 3d data.

### ISSUE THREAD

**Issue by Prakyathkantharaju** [jonmatthis/freemocap#32]
Hello @jonmatthis, As I mentioned in an earlier twitch session I will happy to help with rendering the 3d paths in plotly dash. 

I want a sample dataset that I can test the system with can you point me to it. 

Thanks in advance,
Pk (gliched robot)

**Comment by jonmatthis** [comment]
Thanks for the continued interst! 

Here you go - https://github.com/jonmatthis/freemocap/wiki#sample-data

Check out this script to see the (convoluted) methods I used to generate the matplotlib animation - https://github.com/jonmatthis/freemocap/blob/main/freemocap/play_skeleton_animation.py

As well as this (older, simpler, still quite janky) matplotlib animation code as well - https://github.com/jonmatthis/freemocap/blob/main/freemocap/playskeleton.py

Good luck! 

I'm running off to the woods, soI'll be out of contact until Sunday, but I look forward to checking in on your progress when I'm back in civilization!

**Comment by Prakyathkantharaju** [comment]
Hello @jonmatthis,

I had very little time this weekend; I think I made some good progress. Here is the GitHub repo. [https://github.com/Prakyathkantharaju/dash-c3d](https://github.com/Prakyathkantharaju/dash-c3d)

I have added a small readme for install and usage.

There is some cool functionality I think I can add to the visualization. I have added these ideas to the github project.
