### ISSUE TITLE
How to contribute

### ISSUE THREAD

**Issue by Kickbykick** [jonmatthis/freemocap#33]
Can we have a documentation on how to contribute?

I would really love to read the code and start contributing.

**Comment by 23kcarlson** [comment]
https://github.com/jonmatthis/freemocap/blob/main/CONTRIBUTING.rst

**Comment by Kickbykick** [comment]
Thanks

**Comment by jonmatthis** [comment]
Thanks @Kickbykick  for the question, and @23kcarlson  for the help answering!

Just FYI - This is still a very new project and we're still working out the various ways that we want to organize and handle outside assistance! Hopefully we'll be able to give more specific advice on ways to help out soon!

Thank you so much for your interest in this project and desire to lend a hand! And BIG thank you for your patience as we get our ducks in a row ✨🦆💀 🦆✨
