### ISSUE TITLE
Can multiplayer motion capture be implemented

### ISSUE THREAD

**Issue by zhanghongyong123456** [jonmatthis/freemocap#34]
Will this enable multiplayer motion capture，

**Comment by aaroncherian** [comment]
Having openpose capture multiple people is in the cards - we're working with a lab that's also interested in it, so it is something we'll be looking into at some point.

**Comment by zhanghongyong123456** [comment]
> Having openpose capture multiple people is in the cards - we're working with a lab that's also interested in it, so it is something we'll be looking into at some point.

I am looking forward to it. Thank you for your prompt reply
