### ISSUE TITLE
OpenPose for commercial use?

### ISSUE THREAD

**Issue by emo10001** [jonmatthis/freemocap#37]
I'm very interested in this project as I've been using Blender, and doing mocap for quite some time.  Been toying with OpenCV and Mediapipe...etc.

However, I didn't think OpenPose could be used for commercial work.  Does that mean any mocap derived from this project could NOT be used for a commercial video game or a 3d animated movie to make money?

https://github.com/CMU-Perceptual-Computing-Lab/openpose#license

**Comment by g-rauhoeft** [comment]
This is exactly my concern as well. I love what you guys are doing here, but the OpenPose license is an absolute no-go for anything that could be used beyond science.

**Comment by aaroncherian** [comment]
OpenPose is what we've built FreeMoCap on so far - but the goal of the pipeline is to make it such that you can switch out for a different body tracking system if you'd like. In terms of immediate priorities, getting FreeMoCap running on MediaPipe is on that list.
