### ISSUE TITLE
sessions not getting initialized during recording

### ISSUE THREAD

**Issue by jonmatthis** [jonmatthis/freemocap#4]
===== 2021.07.02 20:07:50 =====
Traceback (most recent call last):
  File "runme_freemocap.py", line 83, in <module>
    sesh, sesh.cam_inputs, sesh.parameterDictionary, sesh.rotationInputs
  File "C:\Users\jonma\Dropbox\GitKrakenRepos\freemocap\freemocap\runcams.py", line 78, in RecordCams
    session.session_settings['recording_parameters'].update({'numCams':session.numCams})
AttributeError: 'Session' object has no attribute 'session_settings'

**Comment by aaroncherian** [comment]
fixed -  a couple of lines in the code from runme_fmc_staged weren't copied over into runme_fmc - and it just so happened to be the couple of lines that started the session
