### ISSUE TITLE
installation requirements or instructions

### ISSUE THREAD

**Issue by backyardbiomech** [jonmatthis/freemocap#61]
I have some undergrad students using this for a class project, and they ran into two installation issues that were easily solved, and should be solvable by either modifying the installation requirements, or just editing the instructions.

All on windows.

The first is that ipython is not automatically installed, so the start instructions fail. For those with new conda installations, after activating the env, `conda install ipython` is a simple fix.

The second error comes after recording, with the end of the Traceback being:

```
~\Miniconda3\envs\freemocap\lib\site-packages\moviepy\video\io\ffmpeg_writer.py in __init__(self, filename, size, fps, codec, audiofile, preset, bitrate, withmask, logfile, threads, ffmpeg_params)
     86             '-s', '%dx%d' % (size[0], size[1]),
     87             '-pix_fmt', 'rgba' if withmask else 'rgb24',
---> 88             '-r', '%.02f' % fps,
     89             '-an', '-i', '-'
     90         ]

TypeError: must be real number, not NoneType
```

This is a problem with moviepy not finding ffmpeg. It's possible to install ffmpeg on windows and add to the path independently, but I prefer to install it in conda with `conda install ffmpeg`. However, moviepy can't find it, so after installing ffmpeg, running 

```
pip uninstall moviepy
pip install moviepy
```
works. I didn't have time to try to install ffmpeg first, but I think just adding it to the env creation line should fix the problem.

**Comment by jonmatthis** [comment]
I'll be pushing a few version (0.0.43) through soon which incorporates a lot of relevant changes - 

I changed the animation making code in `play_skeleton_animation.py` to a method that doesn't require ffmpeg (but is unfortunately quite a bit slower). 

*I* certainly prefer ffmpeg, but I don't want to require users to have it installed for `freemocap` to work. I think there is a way to bundle `ffmpeg` in with the rest of the install, but I don't understand this whole 'pip install' thing well enough to make that work. 

As you noted, `pip install ffmpeg` doesn't seem to work as well as `conda install ffmpeg`, but I don't know how to set things up to install `ffmpeg` through `conda` while installing everything else through `pip`


...so until we get that all figured out, we're going with an option that will keep the install as easy and accessible as possible (even at the cost of a longer wait for the animation to generate at the end ¯\\\_(ツ)_/¯ )


Thanks again for the issue!

I'd love to hear more about what you're working on with this janky little codebase!

**Comment by backyardbiomech** [comment]
It's a bit disappointing to hear that you have to slow down the slowest part of the process to make installation easier, but so be it! Every package I use that requires ffmpeg has installation problems on windows, unless the bulk of the installation is via conda env files (e.g. deeplabcut) so that ffmpeg can be automatically installed via conda before the pip call to the main package. In my own co-developed software [argus](argus.web.unc.edu), we had the same problem with ffmpeg until we shifted installation to a conda env, which I did because of the relative ease of installation deeplabcut that way. I can't think of anyone without a team of developers who has successfully packaged this kind of scientific computer vision software into a one and done app. 

Right now I just threw freemocap at some undergrads in an inquiry based upper level human A&P class. I'm not even teaching it, but my colleague asked if deeplabcut or anipose would be useful, both of which I use in  my research. One group is doing some kind of balance test, and one is doing a reaching task. Freemocap seemed like it would get them data faster compared to training models. So far, so good, I think.

**Comment by jonmatthis** [comment]
Yeah, the guiding principle at the moment is to aim for "ease of use for non-technically trained users" hence opting for a slower process that is easier to install (and still outside the reach of many folks regardless...)

I hadn't thought of switching the whole install to `conda` though! I'll consider that possibility. 

In any case, a lot of this will become a non-issue when we release the alpha version of this code within the next few months. That version is a more-or-less complete re-write of the existing codebase with a wildly different structure and architechture, so hopefully bigger, better, faster and easier to use and grow!

**Comment by abitrolly** [comment]
Why skeleton animation requires `ffmpeg`? And why skeleton is slow without it?

**Comment by jonmatthis** [comment]
@backyardbiomech 

I just realized I could just wrap the `ffmpeg` enabled video exporter in a `try/except` block, and it that fails it falls back on the slower, non-ffmpeg version (and prints instructions on how to install `ffmpeg`) 

:)
