### ISSUE TITLE
how to use OpenPose for body tracking?

### ISSUE THREAD

**Issue by hadi1376tm** [jonmatthis/freemocap#76]
Hi, i have installed cuda and openpose and i can run openpose demo but i didn't found any option in your project to use openpose and it just automatically uses mediapiep by using fmc.RunMe(), how can i get 3d out put using your project with openpose?
should i use  fmc.RunMe(useMediaPipe=false , useOpenPose=true)?

**Comment by hadi1376tm** [comment]
could you please also tell me how to used saved videos instead of camera input?

**Comment by aaroncherian** [comment]
Hi, 

There's one extra flag you should throw in there. fmc.RunMe(useMediaPipe = false, useOpenPose = True, runOpenPose = True). useOpenPose is for parsing the OpenPose data, and the runOpenPose flag is what actually runs the openpose demo. That should solve that problem. 

By using saved videos, do you mean running the program on your own external recordings (say a GoPro or something similar)?

**Comment by hadi1376tm** [comment]
> 
> 
> Hi,
> 
> There's one extra flag you should throw in there. fmc.RunMe(useMediaPipe = false, useOpenPose = True, runOpenPose = True). useOpenPose is for parsing the OpenPose data, and the runOpenPose flag is what actually runs the openpose demo. That should solve that problem.
> 
> By using saved videos, do you mean running the program on your own external recordings (say a GoPro or something similar)?

Thanks,
yes i need to run the program on my own external recordings or on old videos recorded by this program (also on my own calibration parameters if it's possible).
