### ISSUE TITLE
black frames after trimming and syncing videos

### ISSUE THREAD

**Issue by hadi1376tm** [jonmatthis/freemocap#79]
About those black frames after trimming and syncing videos, is there a way to avoid them? those black frame will be a lot if we use different cameras (maybe with different fps) and output 3d model will not be good and continues and when STATIC_IMAGE_MODE in mediapipe is False it also will not accurate (you know why). I tried lowering fps in the program settings but it didn't solve the problem.

**Comment by hadi1376tm** [comment]
here is a code i used while ago to sync my videos, it's so basic but it might be useful:

`import cv2
import time

fps = 20
pic_delay_seconds = 0.05
w = 640
h = 480
capture = cv2.VideoCapture(0)
capture2 = cv2.VideoCapture(1)
# capture = cv2.VideoCapture('1.avi')
# capture2 = cv2.VideoCapture('2.avi')


capture.set(cv2.CAP_PROP_FPS, fps)
capture2.set(cv2.CAP_PROP_FPS, fps)
capture.set(cv2.CAP_PROP_FRAME_WIDTH, w)
capture.set(cv2.CAP_PROP_FRAME_HEIGHT, h)
capture2.set(cv2.CAP_PROP_FRAME_WIDTH, w)
capture2.set(cv2.CAP_PROP_FRAME_HEIGHT, h)

out = cv2.VideoWriter('synced/output.avi', cv2.VideoWriter_fourcc('M','J','P','G'), fps, (w,h))
out2 = cv2.VideoWriter('synced/output2.avi', cv2.VideoWriter_fourcc('M','J','P','G'), fps, (w,h))

img_counter = 0
frame_set = []
start_time = time.time()

while True:
    ret, frame = capture.read()
    ret, frame2 = capture2.read()
    # gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # gray2 = cv2.cvtColor(frame2, cv2.COLOR_BGR2GRAY)

    cv2.imshow('frame', frame)
    cv2.imshow('frame2', frame2)
    out.write(frame)
    out2.write(frame2)

    if time.time() - start_time >= pic_delay_seconds:
        img_name = "synced/frame{}_1.png".format(img_counter)
        img_name2 = "synced/frame{}_2.png".format(img_counter)
        cv2.imwrite(img_name, frame)
        cv2.imwrite(img_name2, frame2)
        print("{} written!".format(img_counter))
        start_time = time.time()
        img_counter += 1

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
capture.release()
capture2.release()
out.release()
out2.release()
cv2.destroyAllWindows()`

**Comment by aaroncherian** [comment]
Hi, yes so if you are using different cameras which might have different FPS rates, it's way more likely that you will see black frames, as the current method of syncing creates a 'master timeline' to sync to based on the average FPS rates between all the cameras, (so if you have different FPS rates, that average will be way off causing black frames while syncing). The FPS setting in the program, which we need to clarify, doesn't apply to the camera FPS settings, but for OpenCV's videowriter/read settings. 

The best ways to mitigate black frames right now are to use the same type of cameras for syncing and to drop the resolution (try out 640x480). The syncing code is among the oldest pieces of code that's been written, and we're likely going to rewrite it from the ground up in coming updates. No promises on the dates, but it's among our priorities.

**Comment by hadi1376tm** [comment]
> Hi, yes so if you are using different cameras which might have different FPS rates, it's way more likely that you will see black frames, as the current method of syncing creates a 'master timeline' to sync to based on the average FPS rates between all the cameras, (so if you have different FPS rates, that average will be way off causing black frames while syncing). The FPS setting in the program, which we need to clarify, doesn't apply to the camera FPS settings, but for OpenCV's videowriter/read settings.
> 
> The best ways to mitigate black frames right now are to use the same type of cameras for syncing and to drop the resolution (try out 640x480). The syncing code is among the oldest pieces of code that's been written, and we're likely going to rewrite it from the ground up in coming updates. No promises on the dates, but it's among our priorities.

Thank you, I'm eagerly waiting for your new updates.
