### ISSUE TITLE
Need to raise a more informative Exception/Error when Charuco points not detected (and allow to continue if only 1 camera is selected)

### ISSUE THREAD

**Issue by jonmatthis** [jonmatthis/freemocap#9]
Currently, if no charuco points are detected, the code fails in this way - 

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jonma\Dropbox\GitKrakenRepos\freemocap\freemocap\__init__.py", line 124, in RunMe
    sesh, board
  File "C:\Users\jonma\Dropbox\GitKrakenRepos\freemocap\freemocap\calibrate.py", line 84, in CalibrateCaptureVolume
    error,merged = cgroup.calibrate_videos(vidnames, board)
  File "C:\Users\jonma\Dropbox\GitKrakenRepos\freemocap\freemocap\fmc_anipose.py", line 1740, in calibrate_videos
    **kwargs
  File "C:\Users\jonma\Dropbox\GitKrakenRepos\freemocap\freemocap\fmc_anipose.py", line 1672, in calibrate_rows
    objp, imgp = zip(*mixed)
ValueError: not enough values to unpack (expected 2, got 0)
```

...which should instead - 

 - [ ] Raise an informative Error/Exception/Whatever thing 
 - [ ]  (Optional) If only one camera is selected, this is a warning. If more than one selected, this is an Error
 -  [ ] (Optional) maybe in general there should be a 'single-camera' mode? so that people can just use this wrapper on their single webcam to play with OpenPose, MediaPipe, DLC, etc?

**Comment by jonmatthis** [comment]
.... at some point I saw an option pop up for one of those bullet points that said 'Convert to issue' which could be useful at some point...

**Comment by aaroncherian** [comment]
@jonmatthis I added this assert statement to get this output. Let me know what the exact wording you would want on the output is. 

![image](https://user-images.githubusercontent.com/17153275/124640437-66062100-de5b-11eb-9d72-ecf7333741b3.png)

**Comment by jonmatthis** [comment]
Nice - How hard would it be to also show the offending camera/video? I.e. "No Charuco points detected in {VideoFileName}"?

**Comment by aaroncherian** [comment]
Mmmm maybe not impossible, but could be a bit time-consuming. 

One issue off the bat is that their camera names might not match up with ours. So I did a two camera recording, and they label their cameras '1' and '2', but the cams I was using were technically 2 and 3 (by the USB input), so we'd have to find some way to match the camera names.

Also, I tried a bunch of times to do a video where one camera could see the board and one couldn't, and the offending camera was always '1', even when I switched the video order around, so I'm not quite sure what's happening there. I'd need to dive into the anipose code more. 

Identifying it by video file name might be possible, but I noticed that they don't pass the list of video file names as an input, so it would take some playing around with and altering their code to so.

**Comment by jonmatthis** [comment]
Gotcha - This is good for now, but we can get back to this at a  later date!

**Comment by Ramdane-HACHOUR** [comment]
Hello, 
I got the same error when I tried to run the code, did you manage to fix it? if so maybe you help me, please!

this is what shows me!
[
![image](https://user-images.githubusercontent.com/95593023/149660942-3a6f1892-cd4f-4487-8ced-984b8e753b9d.png)
](url)
