### ISSUE TITLE
not enough values to unpack (expected 2, got 0)

### ISSUE THREAD

**Issue by Ramdane-HACHOUR** [jonmatthis/freemocap#95]
Hello,

Could someone help me solve this problem, please!
Thank you in advance for your help.

Here is what displays to me, knowing that I used two webcam type cameras.
[
![image](https://user-images.githubusercontent.com/95593023/149661382-7fc42f47-1b99-4a32-a8cb-55bdfa85aa7e.png)
](url)
[
![image](https://user-images.githubusercontent.com/95593023/149661394-4e106e20-1957-48cf-b785-87b9d428b6c5.png)
](url)
[
![image](https://user-images.githubusercontent.com/95593023/149661404-1f0fcd55-301b-4ff1-bc32-bab79bb38632.png)
](url)
[
![image](https://user-images.githubusercontent.com/95593023/149661417-be46c762-c817-4ac7-818c-b8d8c1132f74.png)
](url)

**Comment by abitrolly** [comment]
I am not using Windows, so can't help with it, but if you paste the output as a plain test, it would be at least more readable.

**Comment by Ramdane-HACHOUR** [comment]
@abitrolly Thanks for your feedback.
Could you give me more details on how to do it since? I am a beginner!
thanks in advance.

**Comment by abitrolly** [comment]
You select the text with the mouse, right-click, press "Copy". Then read https://docs.github.com/en/github/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code and Paste into triple backticks.

**Comment by aaroncherian** [comment]
Hey! 

So if you look at the second screenshot, there are two statements. The first one says '0 boards detected', and the second one says '4 boards detected'. This is the Anipose aspect of the pipeline which encompasses the Charuco board calibration. What this means is that out of the 124 frames that were fed in for calibration, for the first video the software didn't find any Charuco boards at all, while for the second it found the Charuco board in only 4 frames.

There are a few possible issues:

The first is that your Charuco board isn't visible enough to the cameras. Light that's really bright or really dim can hamper detection, as can a board that's too small, too far away, or angled weirdly.

The other thing is that this searches through the first 124 frames for the Charuco board, but I noticed your video is about 250 frames. If the Charuco board is only visible towards the end of the video (after frame 124), it wouldn't be in the frames that are fed to Anipose which could lead to this error. If this is the case, you can try a video where you hold the Charuco board up a little quicker. Alternatively, you can specify the number of frames you want to feed to calibration in the `RunMe( )` command with the `calVideoFrameLength = x` flag i.e.

`fmc.RunMe(calVideoFrameLength = 250)`

which would then feed Anipose 250 frames to search for the Charuco board in. If you do:

`fmc.RunMe(calVideoFrameLength=-1)`

the pipeline will automatically use all the frames in the video.

**Comment by Ramdane-HACHOUR** [comment]
Thank you for your remarks, they are interesting, however I respected what you told me and there I have just had this new error. 
I tried the alternatives that the author proposed in comment in (fmc_runme.py and calibrate.py) but I could not solve the problem!
Below are the results I got!

[
![image](https://user-images.githubusercontent.com/95593023/150640408-d3159d47-f663-4ae6-b931-2f0eee12fb2e.png)
](url)
[
![image](https://user-images.githubusercontent.com/95593023/150640420-e29d53b2-b006-4bdc-8006-b9784a370b20.png)
](url)

**Comment by aaroncherian** [comment]
Hey!

Sorry about the delay in response. Did some testing and found the the bug that was causing this problem (so in this case, it wasn't anything about the quality of the recordings/how often the charuco board was seen). There's a new version of freemocap on PyPi now (0.0.46), so try giving that a shot.

**Comment by Ramdane-HACHOUR** [comment]
@aaroncherian, hello!
yes I saw that! I managed to make it work.
Thank you
